# src/main/resources/config.yaml
# 255.255.255.255
app:
  name: redis-lettuce-retry-app
  version: 1.0.0
  settings:
    redisHostName: "Your Server"
    redisPort: 6380
    redisKey: "Your Key"   
    #Seconds
    reconnectMinInterval: 15 
    #Minutes
    reconnectMaxDuration: 30 
    logLevel: DEBUG

