# src/main/resources/config.yaml
# 255.255.255.255
app:
  name: redis-lettuce-retry-app
  version: 1.0.0
  settings:
    redisHostName: "rakeshredis.redis.cache.windows.net"
    redisPort: 6380
    redisKey: "X60UaNDH0xdOThJbeSFurs0uCShKCiieHAzCaDDcV48="   
    #Seconds
    reconnectMinInterval: 15 
    #Minutes
    reconnectMaxDuration: 30 
    logLevel: DEBUG

